"""
Live Gmail Integration Connector
=================================
Fetches incident notifications, alerts, and postmortems from Google Workspace.
Uses token.json (generated by scripts/setup_google_auth.py).

Requirements:
    pip install google-api-python-client google-auth-oauthlib google-auth-httplib2
"""

import os
from pathlib import Path
from typing import Optional

GMAIL_CREDENTIALS_PATH = os.getenv("GMAIL_CREDENTIALS_PATH", "credentials.json")
GOOGLE_TOKEN_PATH      = os.getenv("GOOGLE_TOKEN_PATH", "token.json")

SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
]

def _get_gmail_service():
    """Returns authenticated Gmail service or None if not configured."""
    token_path = Path(GOOGLE_TOKEN_PATH)
    creds_path = Path(GMAIL_CREDENTIALS_PATH)

    if not token_path.exists() and not creds_path.exists():
        return None

    try:
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request
        from googleapiclient.discovery import build

        creds = None
        if token_path.exists():
            creds = Credentials.from_authorized_user_file(str(token_path), SCOPES)

        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
                token_path.write_text(creds.to_json())

        return build("gmail", "v1", credentials=creds)
    except Exception as e:
        print(f"[GMAIL] Could not build service: {e}")
        return None


def fetch_incident_emails(
    query: str = "label:incident OR subject:INC-",
    max_results: int = 10
) -> list[dict]:
    """
    Fetches recent incident emails from Gmail.
    Falls back to simulated data if not authenticated.
    """
    service = _get_gmail_service()

    if service is None:
        # Dry-run: return simulated data so pipeline still works
        return [
            {
                "source": "simulated_gmail",
                "subject": "INC-201: HikariPool connection timeout on checkout-api",
                "from": "alerts@northbeam.studio",
                "snippet": "Staging checkout-api has encountered connection pool exhaustion.",
                "note": "Run scripts/setup_google_auth.py to connect to live Gmail."
            }
        ]

    try:
        results = service.users().messages().list(
            userId="me", q=query, maxResults=max_results
        ).execute()
        messages = results.get("messages", [])
        emails = []

        for msg in messages:
            m = service.users().messages().get(userId="me", id=msg["id"]).execute()
            snippet = m.get("snippet", "")
            headers = {
                h["name"].lower(): h["value"]
                for h in m.get("payload", {}).get("headers", [])
            }
            emails.append({
                "id": msg["id"],
                "subject": headers.get("subject", ""),
                "from": headers.get("from", ""),
                "date": headers.get("date", ""),
                "snippet": snippet,
                "source": "live_gmail",
            })
        print(f"[GMAIL] Fetched {len(emails)} emails matching: {query!r}")
        return emails

    except Exception as e:
        print(f"[GMAIL ERROR] {e}")
        return []


def is_connected() -> bool:
    """Returns True if Gmail API is accessible."""
    return _get_gmail_service() is not None
