"""
Live Google Drive Integration Connector
=======================================
Syncs SOP runbooks and postmortem docs from Google Drive folders into the corpus.
Uses token.json (generated by scripts/setup_google_auth.py).

Requirements:
    pip install google-api-python-client google-auth-oauthlib google-auth-httplib2
"""

import os
import io
from pathlib import Path
from typing import Optional

GOOGLE_TOKEN_PATH    = os.getenv("GOOGLE_TOKEN_PATH", "token.json")
GMAIL_CREDENTIALS_PATH = os.getenv("GMAIL_CREDENTIALS_PATH", "credentials.json")
GDRIVE_FOLDER_ID     = os.getenv("GDRIVE_INCIDENTS_FOLDER_ID", "")

SCOPES = [
    "https://www.googleapis.com/auth/drive.readonly",
]

def _get_drive_service():
    """Returns authenticated Drive service or None if not configured."""
    token_path = Path(GOOGLE_TOKEN_PATH)
    creds_path = Path(GMAIL_CREDENTIALS_PATH)

    if not token_path.exists() and not creds_path.exists():
        return None

    try:
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request
        from googleapiclient.discovery import build

        creds = None
        if token_path.exists():
            creds = Credentials.from_authorized_user_file(str(token_path), SCOPES)

        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
                token_path.write_text(creds.to_json())

        return build("drive", "v3", credentials=creds)
    except Exception as e:
        print(f"[GDRIVE] Could not build service: {e}")
        return None


def sync_gdrive_postmortems(dest_dir: Path) -> list[str]:
    """
    Downloads postmortem markdown files from a shared Drive folder into local corpus.
    Falls back gracefully if not authenticated or folder ID not set.
    """
    service = _get_drive_service()

    if service is None:
        return [
            "Local synthetic corpus active. "
            "Run scripts/setup_google_auth.py and set GDRIVE_INCIDENTS_FOLDER_ID to sync live Drive docs."
        ]

    if not GDRIVE_FOLDER_ID:
        return [
            "Drive auth OK but GDRIVE_INCIDENTS_FOLDER_ID not set in .env. "
            "Get it from your Drive folder URL: drive.google.com/drive/folders/FOLDER_ID"
        ]

    try:
        from googleapiclient.http import MediaIoBaseDownload

        query = f"'{GDRIVE_FOLDER_ID}' in parents and mimeType = 'text/markdown'"
        results = service.files().list(
            q=query, fields="files(id, name, modifiedTime)"
        ).execute()
        files = results.get("files", [])

        if not files:
            return [f"No markdown files found in Drive folder: {GDRIVE_FOLDER_ID}"]

        dest_dir.mkdir(parents=True, exist_ok=True)
        synced = []

        for f in files:
            file_id, name = f["id"], f["name"]
            target = dest_dir / name
            request = service.files().get_media(fileId=file_id)
            buf = io.BytesIO()
            downloader = MediaIoBaseDownload(buf, request)
            done = False
            while not done:
                _, done = downloader.next_chunk()
            target.write_bytes(buf.getvalue())
            synced.append(name)
            print(f"[GDRIVE] Synced: {name}")

        print(f"[GDRIVE] Synced {len(synced)} files from folder {GDRIVE_FOLDER_ID}")
        return synced

    except Exception as e:
        print(f"[GDRIVE ERROR] {e}")
        return []


def list_drive_files(folder_id: str = "") -> list[dict]:
    """List files in a Drive folder (for UI display)."""
    service = _get_drive_service()
    if not service:
        return []
    fid = folder_id or GDRIVE_FOLDER_ID
    if not fid:
        return []
    try:
        results = service.files().list(
            q=f"'{fid}' in parents",
            fields="files(id, name, mimeType, modifiedTime, size)"
        ).execute()
        return results.get("files", [])
    except Exception as e:
        print(f"[GDRIVE ERROR] {e}")
        return []


def is_connected() -> bool:
    """Returns True if Drive API is accessible."""
    return _get_drive_service() is not None
